### ISSUE TITLE
Strings are already immutable in Go

### ISSUE THREAD

**Issue by mewmew** [romshark/Go-1-2-Proposal---Immutability#18]
> Optionally, sep could be declared immutable as well (const string) protecting it from accidental overwrites in the function scope.

Strings are immutable in Go, and thus cannot be overwritten. Or did I misunderstand something? My understanding is that `const string` is equivalent to `string`, as you cannot assign to it.

```go
s[0] = 's' // ERROR
```

**Comment by romshark** [comment]
If this issue is resolved please consider closing it.

**Comment by mewmew** [comment]
Thanks for explaining. I consider the issue resolved.
